name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

assets:
  - assets/images/
  - assets/icons/
  - assets/lottie/

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0
  get: ^4.7.2
  google_fonts: ^6.2.1
  http: ^1.4.0
  intl: ^0.20.2
  lottie: ^3.3.1

flutter:
  uses-material-design: true
